import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rootDir = path.resolve(__dirname, '../../');
const schemaPath = path.resolve(__dirname, './schema.json');

const tsOutputPath = path.resolve(rootDir, 'hmi/lib/telemetry-types.ts');
const cppOutputPath = path.resolve(rootDir, 'firmware/src/comms/telemetry_autogen.h');

// Helper to map C++ type to print format specifier
function getFormatSpecifier(type, precision) {
  if (type === 'float') {
    return `%.${precision}f`;
  } else if (type === 'uint32_t') {
    return '%lu';
  } else if (type === 'int') {
    return '%d';
  }
  return '%s';
}

function getCppSignatureType(type) {
  if (type === 'float') return 'float';
  if (type === 'uint32_t') return 'uint32_t';
  if (type === 'int') return 'int';
  return 'const char*';
}

function run() {
  const rawSchema = fs.readFileSync(schemaPath, 'utf8');
  const schema = JSON.parse(rawSchema);

  // --- Generate TS Interfaces and Parsers ---
  let tsContent = `// =========================================================================\n`;
  tsContent += `//  WARNING: This file is AUTO-GENERATED from shared/telemetry/schema.json.\n`;
  tsContent += `//  Do not edit this file directly. Run "npm run gen" to regenerate.\n`;
  tsContent += `// =========================================================================\n\n`;

  for (const [tag, packet] of Object.entries(schema.packets)) {
    tsContent += `/**\n * ${packet.description}\n */\n`;
    tsContent += `export interface ${packet.name} {\n`;
    for (const field of packet.fields) {
      tsContent += `  /** ${field.description} */\n`;
      tsContent += `  ${field.name}: ${field.tsType}\n`;
    }
    tsContent += `}\n\n`;

    // Parser function
    const hasStringField = packet.fields.some(f => f.tsType === 'string');
    tsContent += `export function parse${packet.name}(parts: (string | number)[]): ${packet.name} {\n`;
    tsContent += `  return {\n`;
    packet.fields.forEach((field, index) => {
      // Index in parts is index + 1 (since index 0 is the tag name, e.g. 'D')
      const partAccess = `parts[${index + 1}]`;
      if (field.tsType === 'boolean') {
        tsContent += `    ${field.name}: Boolean(Number(${partAccess})),\n`;
      } else if (field.tsType === 'string') {
        tsContent += `    ${field.name}: String(${partAccess} ?? '') as ${field.tsType},\n`;
      } else {
        tsContent += `    ${field.name}: Number(${partAccess} ?? 0) as ${field.tsType},\n`;
      }
    });
    tsContent += `  }\n`;
    tsContent += `}\n\n`;
  }

  fs.writeFileSync(tsOutputPath, tsContent, 'utf8');
  console.log(`Generated TS types at: ${tsOutputPath}`);

  // --- Generate C++ Autogen Header ---
  let cppContent = `// =========================================================================\n`;
  cppContent += `//  WARNING: This file is AUTO-GENERATED from shared/telemetry/schema.json.\n`;
  cppContent += `//  Do not edit this file directly. Run "npm run gen" to regenerate.\n`;
  cppContent += `// =========================================================================\n\n`;
  cppContent += `#pragma once\n\n`;
  cppContent += `#include <Arduino.h>\n\n`;

  for (const [tag, packet] of Object.entries(schema.packets)) {
    const formats = packet.fields.map(f => getFormatSpecifier(f.type, f.precision));
    const formatStr = `${tag},${formats.join(',')}\\n`;

    cppContent += `// Telemetry tag '${tag}': ${packet.name}\n`;
    cppContent += `#define TELEMETRY_${tag}_FORMAT "${formatStr}"\n\n`;

    // C++ inline function helper
    const paramsList = packet.fields.map(f => `${getCppSignatureType(f.type)} ${f.name}`).join(', ');
    const argsList = packet.fields.map(f => f.name).join(', ');

    cppContent += `inline int format${packet.name}Packet(char* buf, size_t size, ${paramsList}) {\n`;
    cppContent += `  return snprintf(buf, size, TELEMETRY_${tag}_FORMAT, ${argsList});\n`;
    cppContent += `}\n\n`;
  }

  fs.writeFileSync(cppOutputPath, cppContent, 'utf8');
  console.log(`Generated C++ header at: ${cppOutputPath}`);
}

run();
