// =========================================================================
//  WARNING: This file is AUTO-GENERATED from shared/telemetry/schema.json.
//  Do not edit this file directly. Run "npm run gen" to regenerate.
// =========================================================================

/**
 * Real-time dynamic telemetry loop packet (500 Hz inside firmware, downsampled to 50 Hz on HMI)
 */
export interface DSample {
  /** Timestamp in milliseconds */
  t: number
  /** Joint 1 actual position (rad) */
  th1: number
  /** Joint 2 actual position (rad) */
  th2: number
  /** Joint 1 desired position (rad) */
  th1d: number
  /** Joint 2 desired position (rad) */
  th2d: number
  /** Joint 1 actual velocity (rad/s) */
  v1: number
  /** Joint 2 actual velocity (rad/s) */
  v2: number
  /** Joint 1 desired velocity (rad/s) */
  v1d: number
  /** Joint 2 desired velocity (rad/s) */
  v2d: number
  /** Joint 1 applied control effort/PWM (-255..255) */
  pwm1: number
  /** Joint 1 raw ADC position before filter (rad) */
  th1_raw: number
  /** Joint 2 raw ADC position before filter (rad) */
  th2_raw: number
}

export function parseDSample(parts: (string | number)[]): DSample {
  return {
    t: Number(parts[1] ?? 0) as number,
    th1: Number(parts[2] ?? 0) as number,
    th2: Number(parts[3] ?? 0) as number,
    th1d: Number(parts[4] ?? 0) as number,
    th2d: Number(parts[5] ?? 0) as number,
    v1: Number(parts[6] ?? 0) as number,
    v2: Number(parts[7] ?? 0) as number,
    v1d: Number(parts[8] ?? 0) as number,
    v2d: Number(parts[9] ?? 0) as number,
    pwm1: Number(parts[10] ?? 0) as number,
    th1_raw: Number(parts[11] ?? 0) as number,
    th2_raw: Number(parts[12] ?? 0) as number,
  }
}

/**
 * PID controller gains and feedforward configuration parameters
 */
export interface Gains {
  /** Proportional gain J1 */
  kp1: number
  /** Integral gain J1 */
  ki1: number
  /** Derivative gain J1 */
  kd1: number
  /** Proportional gain J2 */
  kp2: number
  /** Integral gain J2 */
  ki2: number
  /** Derivative gain J2 */
  kd2: number
  /** Stepper driver microstepping configuration */
  mstep: 1 | 2 | 4 | 8 | 16
  /** Inertia Feedforward component blend factor */
  ff1: number
  /** Coriolis/Centrifugal Feedforward component blend factor */
  ff2: number
  /** Gravity Feedforward component blend factor */
  ff3: number
}

export function parseGains(parts: (string | number)[]): Gains {
  return {
    kp1: Number(parts[1] ?? 0) as number,
    ki1: Number(parts[2] ?? 0) as number,
    kd1: Number(parts[3] ?? 0) as number,
    kp2: Number(parts[4] ?? 0) as number,
    ki2: Number(parts[5] ?? 0) as number,
    kd2: Number(parts[6] ?? 0) as number,
    mstep: Number(parts[7] ?? 0) as 1 | 2 | 4 | 8 | 16,
    ff1: Number(parts[8] ?? 0) as number,
    ff2: Number(parts[9] ?? 0) as number,
    ff3: Number(parts[10] ?? 0) as number,
  }
}

/**
 * Advanced physical limits, filter settings, and deadband thresholds
 */
export interface AdvParams {
  /** Maximum velocity (rad/s) */
  vmax: number
  /** Maximum acceleration (rad/s^2) */
  amax: number
  /** Control loop run frequency (Hz) */
  cfreq: number
  /** Maximum torque limit */
  u1max: number
  /** Fractional zero threshold */
  fzt: number
  /** PWM deadband offset */
  pwm_db: number
  /** Tracking Differentiator J1 Bandwidth r */
  td1r: number
  /** Tracking Differentiator J2 Bandwidth r */
  td2r: number
  /** Tracking Differentiator Step Size h */
  td1h: number
  /** Maximum joint speed derivative threshold */
  ddth: number
  /** Deadband engage limit */
  dben: number
  /** Deadband release limit */
  dbrel: number
  /** Deadband velocity threshold */
  dbvel: number
  /** Hold scale Kp multiplier */
  hskp: number
  /** Hold scale Kd multiplier */
  hskd: number
  /** Integral decay rate */
  idecay: number
  /** Nominal torque joint 1 */
  taunom: number
  /** M22 reference component parameter */
  m22ref: number
  /** Tilt angle in degrees */
  alpha_tilt: number
  /** Is tracking differentiator filter enabled */
  td_enabled: number
  /** Is trapezoidal trajectory profiling enabled */
  trap_enabled: number
  /** Joint 2 Ki activation gate (rad) */
  ki2_gate: number
  /** Joint 2 deadband engage limit (rad) */
  db2en: number
  /** Joint 2 deadband release limit (rad) */
  db2rel: number
}

export function parseAdvParams(parts: (string | number)[]): AdvParams {
  return {
    vmax: Number(parts[1] ?? 0) as number,
    amax: Number(parts[2] ?? 0) as number,
    cfreq: Number(parts[3] ?? 0) as number,
    u1max: Number(parts[4] ?? 0) as number,
    fzt: Number(parts[5] ?? 0) as number,
    pwm_db: Number(parts[6] ?? 0) as number,
    td1r: Number(parts[7] ?? 0) as number,
    td2r: Number(parts[8] ?? 0) as number,
    td1h: Number(parts[9] ?? 0) as number,
    ddth: Number(parts[10] ?? 0) as number,
    dben: Number(parts[11] ?? 0) as number,
    dbrel: Number(parts[12] ?? 0) as number,
    dbvel: Number(parts[13] ?? 0) as number,
    hskp: Number(parts[14] ?? 0) as number,
    hskd: Number(parts[15] ?? 0) as number,
    idecay: Number(parts[16] ?? 0) as number,
    taunom: Number(parts[17] ?? 0) as number,
    m22ref: Number(parts[18] ?? 0) as number,
    alpha_tilt: Number(parts[19] ?? 0) as number,
    td_enabled: Number(parts[20] ?? 0) as number,
    trap_enabled: Number(parts[21] ?? 0) as number,
    ki2_gate: Number(parts[22] ?? 0) as number,
    db2en: Number(parts[23] ?? 0) as number,
    db2rel: Number(parts[24] ?? 0) as number,
  }
}

