// =========================================================================
//  WARNING: This file is AUTO-GENERATED from shared/telemetry/schema.json.
//  Do not edit this file directly. Run "npm run gen" to regenerate.
// =========================================================================

/**
 * Real-time dynamic telemetry loop packet (500 Hz ring buffer inside firmware, drained at ~100 Hz, downsampled to 50 Hz on HMI)
 */
export interface DSample {
  /** Timestamp in milliseconds */
  t: number
  /** Joint 1 actual position (rad) */
  th1: number
  /** Joint 2 actual position (rad) */
  th2: number
  /** Joint 1 desired position (rad) */
  th1d: number
  /** Joint 2 desired position (rad) */
  th2d: number
  /** Joint 1 actual velocity (rad/s) */
  v1: number
  /** Joint 2 actual velocity (rad/s) */
  v2: number
  /** Joint 1 desired velocity (rad/s) */
  v1d: number
  /** Joint 2 desired velocity (rad/s) */
  v2d: number
  /** Joint 1 applied control effort/PWM (-255..255) */
  pwm1: number
  /** Velocity feedforward contribution for J1 (fraction of U1_MAX) */
  vff1: number
  /** Joint 1 raw ADC position before filter (rad) */
  th1_raw: number
  /** Joint 2 raw ADC position before filter (rad) */
  th2_raw: number
  /** Total J1 control effort before PWM mapping (same units as U1_MAX) */
  u1_total: number
  /** J1 proportional term output (effort units, same scale as u1_total) */
  p1_out: number
  /** J1 integral term output (effort units, same scale as u1_total) */
  i1_out: number
  /** J1 derivative term output (effort units, same scale as u1_total) */
  d1_out: number
  /** J1 CTC feedforward contribution (effort units, same scale as u1_total) */
  ff1_contrib: number
  /** Joint 1 velocity estimated from encoder (rad/s) — currently unused in firmware */
  v1_enc: number
  /** Joint 1 raw encoder counts — currently unused in firmware */
  enc_count: number
}

export function parseDSample(parts: (string | number)[]): DSample {
  return {
    t: Number(parts[1] ?? 0) as number,
    th1: Number(parts[2] ?? 0) as number,
    th2: Number(parts[3] ?? 0) as number,
    th1d: Number(parts[4] ?? 0) as number,
    th2d: Number(parts[5] ?? 0) as number,
    v1: Number(parts[6] ?? 0) as number,
    v2: Number(parts[7] ?? 0) as number,
    v1d: Number(parts[8] ?? 0) as number,
    v2d: Number(parts[9] ?? 0) as number,
    pwm1: Number(parts[10] ?? 0) as number,
    vff1: Number(parts[11] ?? 0) as number,
    th1_raw: Number(parts[12] ?? 0) as number,
    th2_raw: Number(parts[13] ?? 0) as number,
    u1_total: Number(parts[14] ?? 0) as number,
    p1_out: Number(parts[15] ?? 0) as number,
    i1_out: Number(parts[16] ?? 0) as number,
    d1_out: Number(parts[17] ?? 0) as number,
    ff1_contrib: Number(parts[18] ?? 0) as number,
    v1_enc: Number(parts[19] ?? 0) as number,
    enc_count: Number(parts[20] ?? 0) as number,
  }
}

/**
 * PID controller gains and feedforward configuration parameters
 */
export interface Gains {
  /** Proportional gain J1 */
  kp1: number
  /** Integral gain J1 */
  ki1: number
  /** Derivative gain J1 */
  kd1: number
  /** Proportional gain J2 */
  kp2: number
  /** Integral gain J2 */
  ki2: number
  /** Derivative gain J2 */
  kd2: number
  /** Stepper driver microstepping configuration */
  mstep: 1 | 2 | 4 | 8 | 16
  /** Inertia Feedforward component blend factor */
  ff1: number
  /** Coriolis/Centrifugal Feedforward component blend factor */
  ff2: number
  /** Gravity Feedforward component blend factor */
  ff3: number
}

export function parseGains(parts: (string | number)[]): Gains {
  return {
    kp1: Number(parts[1] ?? 0) as number,
    ki1: Number(parts[2] ?? 0) as number,
    kd1: Number(parts[3] ?? 0) as number,
    kp2: Number(parts[4] ?? 0) as number,
    ki2: Number(parts[5] ?? 0) as number,
    kd2: Number(parts[6] ?? 0) as number,
    mstep: Number(parts[7] ?? 0) as 1 | 2 | 4 | 8 | 16,
    ff1: Number(parts[8] ?? 0) as number,
    ff2: Number(parts[9] ?? 0) as number,
    ff3: Number(parts[10] ?? 0) as number,
  }
}

/**
 * Advanced physical limits, filter settings, and deadband thresholds
 */
export interface AdvParams {
  /** Maximum Cartesian velocity (m/s) */
  vmax: number
  /** Maximum Cartesian acceleration (m/s^2) */
  amax: number
  /** Control loop run frequency (Hz) */
  cfreq: number
  /** Maximum torque limit */
  u1max: number
  /** Fractional zero threshold */
  fzt: number
  /** Fractional zero threshold during kickstart (pct of fzt) */
  fztk: number
  /** Kickstart reduction enabled */
  kspen: number
  /** PWM deadband offset */
  pwm_db: number
  /** Dynamic deadband moving enabled */
  dbmen: number
  /** Deadband engage scale when moving (0.1-1.0) */
  dbens: number
  /** Tracking Differentiator J1 Bandwidth r */
  td1r: number
  /** Tracking Differentiator J2 Bandwidth r */
  td2r: number
  /** Tracking Differentiator Step Size h */
  td1h: number
  /** Maximum joint speed derivative threshold */
  ddth: number
  /** Deadband engage limit */
  dben: number
  /** Deadband release limit */
  dbrel: number
  /** Deadband velocity threshold */
  dbvel: number
  /** Hold scale Kp multiplier */
  hskp: number
  /** Hold scale Kd multiplier */
  hskd: number
  /** Integral decay rate */
  idecay: number
  /** Nominal torque joint 1 */
  taunom: number
  /** M22 reference component parameter */
  m22ref: number
  /** Tilt angle in degrees */
  alpha_tilt: number
  /** Is tracking differentiator filter enabled */
  td_enabled: number
  /** Is trapezoidal trajectory profiling enabled */
  trap_enabled: number
  /** Joint 2 Ki activation gate (rad) */
  ki2_gate: number
  /** Joint 2 deadband engage limit (rad) */
  db2en: number
  /** Joint 2 deadband release limit (rad) */
  db2rel: number
  /** Joint 1 error deadzone in hold mode (rad) */
  err_dz: number
  /** Joint 1 integral freeze threshold near setpoint in hold mode (rad) */
  integral_freeze_thresh: number
  /** Velocity feedforward gain (fraction of U1_MAX per rad/s) */
  kv_vel: number
  /** Velocity feedforward max clamp (fraction of U1_MAX) */
  vff_max_frac: number
  /** Velocity feedforward rate limit per tick (fraction of U1_MAX) */
  vff_dv_max: number
}

export function parseAdvParams(parts: (string | number)[]): AdvParams {
  return {
    vmax: Number(parts[1] ?? 0) as number,
    amax: Number(parts[2] ?? 0) as number,
    cfreq: Number(parts[3] ?? 0) as number,
    u1max: Number(parts[4] ?? 0) as number,
    fzt: Number(parts[5] ?? 0) as number,
    fztk: Number(parts[6] ?? 0) as number,
    kspen: Number(parts[7] ?? 0) as number,
    pwm_db: Number(parts[8] ?? 0) as number,
    dbmen: Number(parts[9] ?? 0) as number,
    dbens: Number(parts[10] ?? 0) as number,
    td1r: Number(parts[11] ?? 0) as number,
    td2r: Number(parts[12] ?? 0) as number,
    td1h: Number(parts[13] ?? 0) as number,
    ddth: Number(parts[14] ?? 0) as number,
    dben: Number(parts[15] ?? 0) as number,
    dbrel: Number(parts[16] ?? 0) as number,
    dbvel: Number(parts[17] ?? 0) as number,
    hskp: Number(parts[18] ?? 0) as number,
    hskd: Number(parts[19] ?? 0) as number,
    idecay: Number(parts[20] ?? 0) as number,
    taunom: Number(parts[21] ?? 0) as number,
    m22ref: Number(parts[22] ?? 0) as number,
    alpha_tilt: Number(parts[23] ?? 0) as number,
    td_enabled: Number(parts[24] ?? 0) as number,
    trap_enabled: Number(parts[25] ?? 0) as number,
    ki2_gate: Number(parts[26] ?? 0) as number,
    db2en: Number(parts[27] ?? 0) as number,
    db2rel: Number(parts[28] ?? 0) as number,
    err_dz: Number(parts[29] ?? 0) as number,
    integral_freeze_thresh: Number(parts[30] ?? 0) as number,
    kv_vel: Number(parts[31] ?? 0) as number,
    vff_max_frac: Number(parts[32] ?? 0) as number,
    vff_dv_max: Number(parts[33] ?? 0) as number,
  }
}

/**
 * CTC feedforward decomposition packet (50 Hz, emitted by firmware during moves)
 */
export interface FSample {
  /** Timestamp in milliseconds */
  t: number
  /** J1 inertia feedforward torque (N·m) */
  inertia1: number
  /** J1 Coriolis/centrifugal feedforward torque (N·m) */
  coriolis1: number
  /** J1 gravity compensation torque (N·m) */
  gravity1: number
  /** J2 inertia feedforward torque (N·m) */
  inertia2: number
  /** J2 Coriolis/centrifugal feedforward torque (N·m) */
  coriolis2: number
  /** J2 gravity compensation torque (N·m) */
  gravity2: number
  /** Total J1 feedforward contribution after blending (effort units) */
  ff1_contrib: number
  /** Total J1 control effort (PID + FF combined) */
  u1_total: number
  /** J1 integrator windup buffer */
  integral1: number
  /** J2 CTC FF converted to velocity increment (rad/s) */
  delta_omega_ff: number
  /** J2 raw velocity before rate limiting (rad/s) */
  omega2_raw: number
  /** J2 integrator windup buffer */
  integral2: number
}

export function parseFSample(parts: (string | number)[]): FSample {
  return {
    t: Number(parts[1] ?? 0) as number,
    inertia1: Number(parts[2] ?? 0) as number,
    coriolis1: Number(parts[3] ?? 0) as number,
    gravity1: Number(parts[4] ?? 0) as number,
    inertia2: Number(parts[5] ?? 0) as number,
    coriolis2: Number(parts[6] ?? 0) as number,
    gravity2: Number(parts[7] ?? 0) as number,
    ff1_contrib: Number(parts[8] ?? 0) as number,
    u1_total: Number(parts[9] ?? 0) as number,
    integral1: Number(parts[10] ?? 0) as number,
    delta_omega_ff: Number(parts[11] ?? 0) as number,
    omega2_raw: Number(parts[12] ?? 0) as number,
    integral2: Number(parts[13] ?? 0) as number,
  }
}

/**
 * PID effort breakdown and loop timing packet (50 Hz)
 */
export interface ESample {
  /** Timestamp in milliseconds */
  t: number
  /** J1 proportional term scaled to PWM units (×255/U1_MAX) */
  p1_out: number
  /** J1 integral term scaled to PWM units */
  i1_out: number
  /** J1 derivative term scaled to PWM units */
  d1_out: number
  /** Microcontroller loop execution time (microseconds) */
  loop_duration_us: number
}

export function parseESample(parts: (string | number)[]): ESample {
  return {
    t: Number(parts[1] ?? 0) as number,
    p1_out: Number(parts[2] ?? 0) as number,
    i1_out: Number(parts[3] ?? 0) as number,
    d1_out: Number(parts[4] ?? 0) as number,
    loop_duration_us: Number(parts[5] ?? 0) as number,
  }
}

/**
 * Cartesian path tracking sample (50 Hz, desired vs actual position in mm)
 */
export interface TPoint {
  /** Desired/ideal X coordinate (mm) */
  xi: number
  /** Desired/ideal Y coordinate (mm) */
  yi: number
  /** Actual measured X coordinate (mm) */
  xa: number
  /** Actual measured Y coordinate (mm) */
  ya: number
}

export function parseTPoint(parts: (string | number)[]): TPoint {
  return {
    xi: Number(parts[1] ?? 0) as number,
    yi: Number(parts[2] ?? 0) as number,
    xa: Number(parts[3] ?? 0) as number,
    ya: Number(parts[4] ?? 0) as number,
  }
}

/**
 * Move start packet — emitted once per trajectory, triggers HMI buffer clear and recording state
 */
export interface MoveStart {
  /** Start X coordinate (mm) */
  x0: number
  /** Start Y coordinate (mm) */
  y0: number
  /** Target X coordinate (mm) */
  xf: number
  /** Target Y coordinate (mm) */
  yf: number
}

export function parseMoveStart(parts: (string | number)[]): MoveStart {
  return {
    x0: Number(parts[1] ?? 0) as number,
    y0: Number(parts[2] ?? 0) as number,
    xf: Number(parts[3] ?? 0) as number,
    yf: Number(parts[4] ?? 0) as number,
  }
}

/**
 * Move continuation for L-shape second leg — same format as M but signals HMI to NOT clear buffers
 */
export interface MoveContinue {
  /** Intermediate start X coordinate (mm) */
  x0: number
  /** Intermediate start Y coordinate (mm) */
  y0: number
  /** Target X coordinate (mm) */
  xf: number
  /** Target Y coordinate (mm) */
  yf: number
}

export function parseMoveContinue(parts: (string | number)[]): MoveContinue {
  return {
    x0: Number(parts[1] ?? 0) as number,
    y0: Number(parts[2] ?? 0) as number,
    xf: Number(parts[3] ?? 0) as number,
    yf: Number(parts[4] ?? 0) as number,
  }
}

/**
 * Move done / settled packet — emitted once when trajectory completes and settle condition is met
 */
export interface MoveDone {
  /** Final settled X coordinate (mm) */
  xf: number
  /** Final settled Y coordinate (mm) */
  yf: number
}

export function parseMoveDone(parts: (string | number)[]): MoveDone {
  return {
    xf: Number(parts[1] ?? 0) as number,
    yf: Number(parts[2] ?? 0) as number,
  }
}

/**
 * Position heartbeat — emitted on boot and in response to getgains
 */
export interface Position {
  /** Current X coordinate from forward kinematics (mm) */
  x: number
  /** Current Y coordinate from forward kinematics (mm) */
  y: number
  /** Joint 1 angle (rad) */
  th1: number
  /** Joint 2 angle (rad) */
  th2: number
}

export function parsePosition(parts: (string | number)[]): Position {
  return {
    x: Number(parts[1] ?? 0) as number,
    y: Number(parts[2] ?? 0) as number,
    th1: Number(parts[3] ?? 0) as number,
    th2: Number(parts[4] ?? 0) as number,
  }
}

/**
 * Trajectory queue status — emitted when pending move state changes
 */
export interface QueueStatus {
  /** 1 if a move is queued, 0 otherwise */
  pending: number
  /** Queued trajectory destination X (mm) */
  pending_x: number
  /** Queued trajectory destination Y (mm) */
  pending_y: number
}

export function parseQueueStatus(parts: (string | number)[]): QueueStatus {
  return {
    pending: Number(parts[1] ?? 0) as number,
    pending_x: Number(parts[2] ?? 0) as number,
    pending_y: Number(parts[3] ?? 0) as number,
  }
}

/**
 * Operating mode indicator — emitted on every mode change
 */
export interface Mode {
  /** Mode name: IDLE | SCARA | ZN | TEST */
  mode: string
}

export function parseMode(parts: (string | number)[]): Mode {
  return {
    mode: String(parts[1] ?? '') as string,
  }
}

/**
 * Emergency stop status — emitted on estop/resume
 */
export interface EStop {
  /** 1 if emergency stop is active, 0 if cleared */
  active: number
}

export function parseEStop(parts: (string | number)[]): EStop {
  return {
    active: Number(parts[1] ?? 0) as number,
  }
}

