[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -O2
    -I include

upload_speed   = 921600
monitor_speed  = 921600
monitor_filters = direct

upload_protocol = esptool